return {
    author_replay   = require("exoua.types.author_replay"),
    brush           = require("exoua.types.brush"),
    color           = require("exoua.types.color"),
    enums           = require("exoua.types.enums"),
    invocation      = require("exoua.types.invocation"),
    layer           = require("exoua.types.layer"),
    level           = require("exoua.types.level"),
    local_level     = require("exoua.types.local_level"),
    metadata        = require("exoua.types.metadata"),
    object          = require("exoua.types.object"),
    object_property = require("exoua.types.object_property"),
    old_script      = require("exoua.types.old_script"),
    pattern         = require("exoua.types.pattern"),
    prefab          = require("exoua.types.prefab"),
    theme           = require("exoua.types.theme"),
    varint          = require("exoua.types.varint"),
    vec2            = require("exoua.types.vec2"),
    novascript      = require("exoua.types.novascript"),
}
